service:
  name: flask_app_service
  identifier: flask_app_service
  serviceDefinition:
    type: Kubernetes
    spec:
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: docker_connector
                imagePath: brainstrom/docker_harness
                tag: <+input>
                digest: ""
              identifier: docker_hub_artifacts
              type: DockerRegistry
  gitOpsEnabled: false
  orgIdentifier: default
  projectIdentifier: harness_python
