apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: default  # Change this if you want to use a different namespace
spec:
  type: LoadBalancer  # You can change this to NodePort if you are using Minikube
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-app
