service:
  name: flask_app_service_latest
  identifier: flask_app_service_latest
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: flask_app_service
            type: ReleaseRepo
            spec:
              store:
                type: Github
                spec:
                  connectorRef: github_harness
                  gitFetchType: Branch
                  paths:
                    - harness_python_app_demo /service.yaml
                  branch: master
        - manifest:
            identifier: flask_app_deployment
            type: DeploymentRepo
            spec:
              store:
                type: Github
                spec:
                  connectorRef: github_harness
                  gitFetchType: Branch
                  paths:
                    - harness_python_app_demo /deployment.yaml
                  branch: master
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: docker_connector
                imagePath: brainstrom/docker_harness
                tag: <+input>
                digest: ""
              identifier: docker_harness
              type: DockerRegistry
  gitOpsEnabled: true
  orgIdentifier: default
  projectIdentifier: harness_python
